// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Command: npx gltfjsx@6.2.10 empaque_prueba.gltf 
// */

// import React, { useRef } from 'react'
// import { useGLTF } from '@react-three/drei'

// export function Model(props) {
//   const { nodes, materials } = useGLTF('/empaque_prueba.gltf')
//   return (
//     <group {...props} dispose={null}>
//       <mesh geometry={nodes.empaque.geometry} material={nodes.empaque.material} />
//     </group>
//   )
// }

// useGLTF.preload('/empaque_prueba.gltf')

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const gltf = useGLTF('/empaque_prueba.gltf')
  return (
    <primitive object={gltf.scene} />
  )
}

useGLTF.preload('/empaque_prueba.gltf')
